.set NUMNOTAS, 58

arrayNotas:
    .word   SI           
	.word   DOH          
	.word   REH

	.word   REH 
	.word   DOH
	.word   SI
	.word   LA

	.word   SOL
	.word   SOL
	.word   LA         
	.word   SI

	.word   SI        
	.word   LA          
	.word   LA         
	
	.word   SI         
	.word   DOH            
	.word   REH

	.word   REH
    .word   DOH          
	.word   SI
    .word   LA

    .word   SOL
	.word   SOL
	.word   LA         
	.word   SI

	.word   LA
	.word   SOL
    .word   SOL

    .word   LA        
	.word   SI         
	.word   SOL         
	
	.word   LA        
	.word   SI            
	.word   DOH
	.word   SI            
    .word   SOL

	.word   LA
	.word   SI 
    .word   DOH        
	.word   SI
    .word   LA

    .word   SOL
    .word   LA
    .word   RE

	.word   SI         
	.word   DOH         
	.word   REH

	.word   REH           
	.word   DOH
	.word   SI            
    .word   LA

	.word   SOL
	.word   SOL        
	.word   LA
	.word   SI

    .word   LA
    .word   SOL
    .word   SOL

arrayDuraciones:	
	.word BL
	.word NG
	.word NG

	.word NG	
	.word NG
	.word NG
	.word NG

	.word NG
	.word NG
	.word NG
	.word NG

	.word NG
	.word COR
	.word BL
	
	.word BL
	.word NG
	.word NG

	.word NG	
	.word NG
	.word NG
	.word NG

	.word NG	
	.word NG
	.word NG
	.word NG

    .word NG
	.word COR   	
	.word BL 
  	
	.word BL   	
	.word NG
	.word NG

	.word NG   	
	.word COR 
	.word COR   	
	.word NG   	
	.word NG   	
	
	.word NG   	
	.word COR 
	.word COR   	
	.word NG   	
	.word NG   	
	
	.word NG   	
	.word NG   	
	.word BL

	.word BL      
	.word NG
	.word NG

	.word NG	
	.word NG
	.word NG
	.word NG
	
	.word NG	
	.word NG
	.word NG
	.word NG

	.word NG
	.word COR
	.word BL 

